apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
  app: myapp
spec:
  containers:
  - name: cont-1
    image: avinashg0/secret
    ports:
     - containerPort: 3000
    envFrom:
    - configMapRef:
        name: configmap-env
    - secretRef:
        name: secret-env